### PR TITLE
Update list of database service adapters

### PR DESCRIPTION
**Pull request by compwright**
* Alphabetize database adapters
* Add feathers-bee-queue

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the pull request. We should definitely add `feathers-bee-queue` but I'd prefer to have the adapters that officially fully support the Feathers query syntax at the top like it was before.

**Comment by compwright** [comment]
Got it - I'll update so that the official plugins are at the top. I guess I failed to notice that they were thus designated.

**Comment by compwright** [comment]
@daffl should be good too go on this now.

**Comment by daffl** [comment]
Great, thank you!

**Pull request merged**
